# See the full configuration reference: https://rioterm.com/docs/config
theme = "dracula"
# required to user current-working-directory
use-fork = false

[editor]
program = "nvim"
args = []

[fonts]
size = 18

[fonts.regular]
family = "Jetbrains Mono"
style = "Medium"

[fonts.bold]
family = "Jetbrains Mono"
style = "Bold"

[fonts.italic]
family = "Jetbrains Mono"
style = "Italic"

[fonts.bold_italic]
family = "Jetbrains Mono"
style = "Bold Italic"

[window]
opacity = 0.96

[navigation]
current-working-directory = true

[bindings]
keys = [
    #Create splits
    { key = "r", with = "control | shift", action = "SplitRight" },
    { key = "F4", with = "", action = "SplitRight" },
    { key = "d", with = "control | shift", action = "SplitDown" },
    { key = "F5", with = "", action = "SplitDown" },
    #Split move
    { key = "l", with ="alt", action ="SelectNextSplit"},
    { key = "right", with ="control", action ="SelectNextSplit"},
    { key = "right", with ="alt", action ="SelectNextSplit"},
    { key = "h", with ="alt", action ="SelectPrevSplit"},
    { key = "left", with ="control", action ="SelectPrevSplit"},
    { key = "left", with ="alt", action ="SelectPrevSplit"},
    #Split resize - not working - issues report #1550
    { key = "up", with = "control | shift | alt", action = "MoveDividerUp" },
    { key = "k", with = "control | shift | alt", action = "MoveDividerUp" },
    { key = "down", with = "control | shift | alt", action = "MoveDividerDown" },
    { key = "j", with = "control | shift | alt", action = "MoveDividerDown" },
    { key = "left", with = "control | shift | alt", action = "MoveDividerLeft" },
    { key = "h", with = "control | shift | alt", action = "MoveDividerLeft" },
    { key = "l", with = "control | shift | alt", action = "MoveDividerRight" },
]
