#Desktop
wallpaper {
    monitor = DVI-D-1
    path = ~/.config/wallpapers/cyberpunk-anime-city-art_2000x1192.jpg
    #contain|cover|tile|fill, default is cover
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    #path = ~/.config/wallpapers/cyberpunk-style_3840x1633.jpg
    path = .config/wallpapers/
    timeout = 600
    fit_mode = cover
}

#Laptop
wallpaper {
    monitor = eDP-1
    # path = ~/.config/wallpapers/nier-automata-001_1920x1080.png
    path = ~/.config/wallpapers/
    timeout = 300
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/wallpapers/unix_1920x1080.jpg
    fit_mode = cover
}

splash = false
