#Desktop
wallpaper {
    monitor = DVI-D-1
    path = ~/.config/wallpapers/cyberpunk-anime-city-art_2000x1192.jpg
    #contain|cover|tile|fill, default is cover
    fit_mode = cover
}

wallpaper {
    monitor = DVI-D-1
    path = ~/.config/wallpapers/cyberpunk-style_3840x1633.jpg
    fit_mode = cover
}

#Laptop
wallpaper {
    monitor = eDP-1
    path = .config/wallpapers/cyberpunk-anime-city-art_4096x2304.jpg
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/.config/wallpapers/unix_1920x1080.jpg
    fit_mode = cover
}
