general {
    disable_loading_bar = false
    grace = 0
}

background {
    monitor =
    # path = screenshot
    path = /usr/share/backgrounds/archlinux/gritty.png
    blur_passes = 2
    blur_size = 2
}
#Clock
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    font_size = 50
    position = 0, 80
    halign = center
    valign = center
}
#Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .80)
    font_size = 19
    font_family = SF Pro Display Bold
    position = 0, 10
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 320, 55
    outline_thickness = 0
    dots_size = 0.2 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.2 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgba(255, 255, 255, 0.1)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    font_family = SF Pro Display Bold
    placeholder_text = <i><span foreground="##ffffff99">🔒  Enter Pass</span></i>
    hide_input = false
    position = 34, -268
    halign = center
    valign = center
}
